services:
    sonata.admin.faq:
        class: AppBundle\Admin\FAQAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "FAQ" }
        arguments:
            - ~
            - AppBundle\Entity\FAQ
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]

    sonata.admin.faq_category:
        class: AppBundle\Admin\FAQCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Категории FAQ" }
        arguments:
            - ~
            - AppBundle\Entity\FAQCategory
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]

    sonata.admin.line:
        class: AppBundle\Admin\LineAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Направления" }
        arguments:
            - ~
            - AppBundle\Entity\Line
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]

    sonata.admin.case_area:
        class: AppBundle\Admin\CaseAreaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Case Area" }
        arguments:
            - ~
            - AppBundle\Entity\CaseArea
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]

    sonata.admin.frame:
        class: AppBundle\Admin\FrameAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Каркас" }
        arguments:
            - ~
            - AppBundle\Entity\Frame
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]