AppBundle\Entity\CaseArea:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        icon:
            type: string
            length: 255
        preview:
            type: string
            length: 1000
        description:
            type: text
        button_title:
            type: string
            length: 30
        updated:        # changed when files are uploaded, to force preUpdate and postUpdate to fire
            type:         datetime
            nullable:     true
        weight:
            type: integer
        rawDescription:
            type: text
        descriptionFormatter:
            type: string
            length: 255
        active:
            type: boolean
            nullable: false
    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]
