AppBundle\Entity\FAQ:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        question:
            type: string
            length: 255
        answer:
            type: text
        weight:
            type: integer
    lifecycleCallbacks: {  }
