AppBundle\Entity\FAQCategory:
    type: entity
    table: faq_category
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        weight:
            type: integer
    lifecycleCallbacks: {  }
